USE test;

CREATE TABLE IF NOT EXISTS employees
ENGINE="FEDERATED" DEFAULT CHARSET=ucs2
CONNECTION='test_employees';

CREATE TABLE IF NOT EXISTS titles
ENGINE="FEDERATED" DEFAULT CHARSET=ucs2
CONNECTION='test_titles';

CREATE TABLE IF NOT EXISTS salaries
ENGINE="FEDERATED" DEFAULT CHARSET=ucs2
CONNECTION='test_salaries';

SHOW WARNINGS;

flush /*!50503 binary */ logs;
