CREATE TABLE IF NOT EXISTS employees
ENGINE="FEDERATED" DEFAULT CHARSET=ucs2
CONNECTION='test.employees';

CREATE TABLE IF NOT EXISTS titles
ENGINE="FEDERATED" DEFAULT CHARSET=ucs2
CONNECTION='test.titles';

CREATE TABLE IF NOT EXISTS salaries
ENGINE="FEDERATED" DEFAULT CHARSET=ucs2
CONNECTION='test.salaries';

SHOW WARNINGS;

flush /*!50503 binary */ logs;
