USE test;

CREATE TABLE IF NOT EXISTS departments
ENGINE="FEDERATED" DEFAULT CHARSET=ucs2
CONNECTION='test_departments';

CREATE TABLE IF NOT EXISTS dept_manager
ENGINE="FEDERATED" DEFAULT CHARSET=ucs2
CONNECTION='test_dept_manager';

CREATE TABLE IF NOT EXISTS dept_emp
ENGINE="FEDERATED" DEFAULT CHARSET=ucs2
CONNECTION='test_dept_emp';

SHOW WARNINGS;

flush /*!50503 binary */ logs;
